- name: Replace a node1 ip
  lineinfile:
    path: /etc/hosts
    regexp: '^192\.168\.4\.5'
    line: 192.168.4.5 node1.ios.in.ua node1
    owner: root
    group: root
    mode: '0644'

- name: Replace a node2 ip
  lineinfile:
    path: /etc/hosts
    regexp: '^192\.168\.4\.6'
    line: 192.168.4.6 node2.ios.in.ua node2
    owner: root
    group: root
    mode: '0644'

- name: Replace a node3 ip
  lineinfile:
    path: /etc/hosts
    regexp: '^192\.168\.4\.7'
    line: 192.168.4.7 node3.ios.in.ua node3
    owner: root
    group: root
    mode: '0644'

- name: Replace a node4 ip
  lineinfile:
    path: /etc/hosts
    regexp: '^192\.168\.4\.8'
    line: 192.168.4.8 node4.ios.in.ua node4
    owner: root
    group: root
    mode: '0644'

- name: Replace a bu.ra ip
  lineinfile:
    path: /etc/hosts
    regexp: '^192\.168\.4\.16'
    line: 192.168.4.16 bu.ra bu
    owner: root
    group: root
    mode: '0644'